#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define MQTT_HOST "YOUR_MQTT_BROKER"
#define MQTT_PORT 1883
#define MQTT_USER "YOUR_MQTT_USER"
#define MQTT_PASSWORD "YOUR_MQTT_PASSWORD"
#define MQTT_CLIENT_ID "smart-agriculture-esp32"
#define MQTT_TOPIC_TELEMETRY "farm/plot1/telemetry"
#define SOIL_DRY_THRESHOLD 1800
